### ISSUE TITLE
`Package.json` structure: clean and organised

### ISSUE THREAD

**Issue by zurda** [FAC-Sixteen/week2-project-RRJD#19]
`package.json` looks very clean. By that I mean: all the testing packages are installed as dev dependencies, and you created different scripts for different processes. Great Job! 

Two things to note: 
- For your scripts, you usually wouldn't like to call a script by a package name (e.g `nodemon`). This might create confusion when someone runs your project. Consider naming the script according to the end result rather than the tools you use. For example, if the end result of running the `nodemon` script is `self running tests` (from your README) -> perhaps the name for the script can be `live`, `live-update`. It's up to you, but you want to keep things as self explanatory as possible. 
- Consider adding a script to simultaneously run tests and coverage simultaneously. This isn't necessary, but it's a good thing to try. Also, learning how to pipe scripts together (i.e running one script after another) is something you'll do moving forward so worth giving it a try.

**Comment by RymaTech** [comment]
Sorted. Thanks for the help :)

**Comment by zurda** [comment]
```
Consider adding a script to simultaneously run tests and coverage simultaneously. This isn't necessary, but it's a good thing to try. Also, learning how to pipe scripts together (i.e running one script after another) is something you'll do moving forward so worth giving it a try.
```

This is something that Jest will make extremely easier! IF it gives you any trouble don't bother but remember the comment for when you give Jest a try :)
