### ISSUE TITLE
Object nesting - double 'description'

### ISSUE THREAD

**Issue by seabasshoang** [FAC-Sixteen/week2-project-RRJD#20]
You have declared your 'task list' object by filling an object with smaller sub-objects:

<img width="638" alt="Declaration of tasklist object" src="https://user-images.githubusercontent.com/35779506/54425438-3fad9c00-470d-11e9-9714-79dfb060cbd4.png">

This creates a strange nesting arrangement where description is doubled up:

<img width="702" alt="Console log of tasklist object" src="https://user-images.githubusercontent.com/35779506/54425444-450ae680-470d-11e9-953a-875a0a5ff9e1.png">

You might be able to find a simpler way of declaring the object. 💃🐬

**Comment by jokosanyang** [comment]
Sorry, can't fix it. :)

**Comment by RohanSSS** [comment]
actually fixable, joko has done it
