### ISSUE TITLE
ES6 in tests (let vs const)

### ISSUE THREAD

**Issue by zurda** [FAC-Sixteen/week2-project-RRJD#22]
Your test structure is looking great, but it's worth noting `const` vs `let`: 

```
test('deleteTodo should not edit array todo', function (t) {
  let actual = ['edit', 'editing'];
  let expected = ['edit', 'editing'];
  logic.deleteTodo(actual);
  t.deepEqual(actual, expected, 'deleteTodo edit array');
  t.end();
});
```

In this case, for example, your `actual` and `expected` variables are constant, so they should be declared using `const`.

**Comment by Dalmano** [comment]
variables have been changed, they are now being declared using const
