### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by zurda** [FAC-Sixteen/week2-project-RRJD#25]
Amazing job on styling considering the time constraints on this project! You wrote on the readme this was your last task, but it doesn't show. The color theme seems to be very thought out, the fonts are also pleasant to look at, and the general feel of the page is great. 

When you think of a todo list as an app that can be stressful since it lists all the things you never get around to doing - having a pleasant and calming colour theme is extremely important for the user experience. So again - great job!

**Comment by jokosanyang** [comment]
Thank you!! Yellow is a great colour.
