### ISSUE TITLE
Bang! 

### ISSUE THREAD

**Issue by seabasshoang** [FAC-Sixteen/week2-project-RRJD#28]
Great use of the logical 'not' operator to create a toggle!

<img width="444" alt="Screenshot 2019-03-15 at 11 01 28" src="https://user-images.githubusercontent.com/35779506/54427241-ce241c80-4711-11e9-92ff-8ab9cdcd7a4d.png">

![Bang bang](https://media.giphy.com/media/PqSbSRO7n97na/giphy.gif)

**Comment by jokosanyang** [comment]
Your GIF game is on fire.
